### PR TITLE
Refactored OctgnChrome to window decorators

### PR DESCRIPTION
**Pull request by boykathemad**
This is basically the refactoring of Controls.OctgnChrome into a DecorableWindow and possible decorators.
The original chrome is placed in a decorator as-is, there is also a new decorator that looks pretty much the same as the old one, with some improvements, and there is the native decorator, which basically does no decorating.
There is a new combobox option in the Options dialog for choosing which decorator to use.

This is obviously not ready for merging, just wanted to start the conversation...
If someone could take a look and point out any problems, I'd be happy to resolve them.

---
#### This is the resubmit of the previous pull request #1530 fixing the commit author mistake.

### CODE REVIEW

**Comment by boykathemad** [comment]
The CLA check is fine now.

**Comment by kellyelton** [comment]
Alright, please update your file recentchanges.txt with your changes

change - Your name(or username or whatever)

This file is what we use to generate our changelog

**Comment by boykathemad** [comment]
I added the change log message, I hope it's ample enough. I also fixed an issue with fullscreen.
Let me know if there's anything wrong.

**Comment by kellyelton** [comment]
Alright. So first question I have is, what did you do to improve the OctgnShell? The only difference I see is that there isn't a border around the window.

**Comment by boykathemad** [comment]
Most of the improvements on the OctgnShell decorator are done by the WindowChrome(Microsoft.Windows.Shell) instance, which handles many window interactions natively. It handles resize(also hides resize cursors for windows that aren't resizable) and titlebar actions(moving, double-click maximize and double click on top border) natively, conserves space when maximized by reducing window padding and allows window animations(like minimize, maximize and restore/show) to work properly. With little added code, I made the context menu appear when clicking on the window icon as well as closing it on double-click. So overall the OctgnShell decorator acts as any native window in Windows.
Now the caveat: it does not support window transparency, so the corresponding option is ignored. Because of this it cannot show the semi-transparent border, so I decided to drop it altogether. If you think the border is necessary I can add it, but it has to be a solid color.

**Comment by kellyelton** [comment]
Yeah. It may have been my want for that border that caused the window to end up like that.

I like the idea of letting windows handle all of those things, though they've been working pretty seamlessly for us, so there's really no reason to do it.that way, except to keep things sane. That being said I'm ok with replacing the old(however functional) old window just so we can clean things up a bit. So if you want to just remove that that's fine with me.

Also I don't know if you're interested at all, but what I would like to see is, I have a branch called NewUI with a whole new window. If you could incorporate that into this system that would be awesome as well.

So to wrap it up, what I'd like to see to accept this pull request is for you to get rid of the old OCTGN chrome in favor of your new one(If you're interested in merging in the NewUI branch, that should be a separate pull request)

**Comment by kellyelton** [comment]
Just checking to see if you're still interested in finishing this up?

**Comment by kellyelton** [comment]
Hey @boykathemad  just poking you again about this. Would like to pull it in.

**Comment by boykathemad** [comment]
@kellyelton Sorry for not responding sooner. I was unable to work due to health issues. I will try to finalize this PR this weekend.

**Comment by kellyelton** [comment]
Thanks it's no rush, hope you're doing well. I was just worried you abandoned it.

**Comment by boykathemad** [comment]
Finally got around to finish this. Let me know if I need to do anything else before you can merge this. FYI the "Use Windows Transparency" option is not used by the new decorator, but since it may be used by future decorators (I plan on making an Android Netrunner themed decorator in the future), I left it there.
I checked out the NewUI branch and I could probably bring that up to date as soon as I have time in mid-February. So once this is done I'll come back to that.

**Comment by kellyelton** [comment]
Thanks, this will be great!

**Comment by kellyelton** [comment]
`Controls\WindowDecorator.cs(55,56): error CS1519: Invalid token '=' in class, struct, or interface member declaration`

If you could fix this in a new pull request that'd be awesome. If you don't think you'll have time, just let me know and we can have someone fix it.

**Comment by kellyelton** [comment]
Alright so I finally took a look at it.

The issue is you're doing this `public bool IsUndoable { get; protected set; } = false;`

This is a c# 6.0 feature, and our build system wasn't use that. It is now, so don't worry about it.

Also it really doesn't even make sense to set that because bools always default to false, but it's not worth changing at this point.

Thanks again for the commit

**Comment by boykathemad** [comment]
I was just about to say that it's a C# 6 feature, and I could change that, but thanks for the resolution and explanation.

**Comment by brine** [comment]
there's a crucial bug in the PR currently, where you can't move the OCTGN window to a different monitor.  I dont know what other bugs are there so far but this one's pretty big for multi-monitor setups

**Comment by boykathemad** [comment]
I think the problem is with DecorableWindow.OnLocationChanged which used to be the following in OctgnChrome:
```
private void OnLocationChanged(object sender, EventArgs eventArgs)
{
    var myRec = new System.Drawing.Rectangle((int)this.Left + 50, (int)this.Top + 50, (int)this.Width - 50, (int)this.Height - 50);
    var screens = Screen.AllScreens;
    if (!screens.Any(x => x.Bounds.IntersectsWith(myRec)))
    {
        var bounds = Screen.PrimaryScreen.Bounds;
        this.Left = ((bounds.Right - bounds.Left) / 2) + (Width / 2);
        this.Top = ((bounds.Bottom - bounds.Top) / 2) + (Height / 2);
    }
    System.IntPtr handle = (new WinInterop.WindowInteropHelper(this)).Handle;
    //WinInterop.HwndSource.FromHwnd(handle).AddHook(new WinInterop.HwndSourceHook(WindowProc));
}
```
which I tried to changed to a pure WPF solution, at which I have failed miserably, apparently.
Now, I have no multi-monitor setup to test this, so if anyone could reinstate the above code to DecorableWindow and see if it works, and possibly submit a fix for this, that would be great.

**Pull request merged**
