### PR TITLE
fix #1869

### LINKED ISSUE #1869: Card image zoom falls behind the extended chat
Example

### PR DESCRIPTION
**Pull request by BenMatteson**
card zoom now appears over extended chat
also slight tweak to turn counter/phase panel area to be more accommodating of variable name length and minimize wasted space.

### CODE REVIEW

**Comment by brine** [comment]
I assume this will work in combination with my fixes to the limited deck editor window #1878

**Comment by BenMatteson** [comment]
Oh right, the limited editor... I haven't tested what it does with that, it shouldn't conflict with your pull, but it might have other issues. I might not be able to test it for a bit

**Comment by BenMatteson** [comment]
ok, looks the same in the limited editor, and I'm confident it won't conflict with your changes.

**Comment by brine** [comment]
Ok cool, just making sure cuz I remember there was some weird wpf layering and z index shenanigans going on in that play window

**Comment by BenMatteson** [comment]
yeah, I wasn't really sure what to look for, but as far as I can tell it's still on top of everything like it's supposed to be, is there anything specific I should check?

**Comment by brine** [comment]
Nah it looks fine, we’ll just make a mental note to check it once everything gets merged in

**Pull request merged**
