### PR TITLE
put global player back in front

### PR DESCRIPTION
**Pull request by BenMatteson**
the lazy way

### CODE REVIEW

**Comment by brine** [comment]
I think we should be looking at reverting this line first and seeing if it was just an oversight
https://github.com/octgn/OCTGN/pull/1856/files#diff-604d3217627ae5bc51892cde15990bd1

**Comment by BenMatteson** [comment]
I did that first, there's code in counters that requires local player to exist first: 
https://github.com/octgn/OCTGN/blob/master/octgnFX/Octgn/Play/Counter.cs#L35

I don't know if that's the only place that has issues, and if it is if there's an easy way to fix it, I just took the easy route. if somebody wants to dig into it then by all means, but I'm just putting the lazy way out there.

**Comment by BenMatteson** [comment]
though that does look like that's raising events for the local player for every counter change on any player which seems like a bug, so maybe it should get looked at

**Comment by brine** [comment]
https://github.com/brine/OCTGN/commit/5f4173d600e203f42f59a689e86f2d34dd5db225

@kellyelton Here's a different interpretation of that CanChange counter property... Not quite sure what the intent was behind the event handler

**Comment by kellyelton** [comment]
> [brine@5f4173d](https://github.com/brine/OCTGN/commit/5f4173d600e203f42f59a689e86f2d34dd5db225)
> 
> @kellyelton Here's a different interpretation of that CanChange counter property... Not quite sure what the intent was behind the event handler

I don't understand

**Pull request merged**
