### PR TITLE
Removed subscriber requirement to add images via drag and drop

### LINKED ISSUE #1682: remove subscriber lock for loading card images in deck editor
this has been discussed as a possibility.  Some games don't have reliable image packs (for many possible reasons) and restricting this feature for users who may need to get the images on their own isn't beneficial.

### PR DESCRIPTION
**Pull request by iGemini**
Fixes #1682

Just putting this here, decision pending.

### CODE REVIEW

**Comment by Soul1355** [comment]
might want to change the loading message that mentions this too

**Comment by brine** [comment]
I mean technically its still true

**Comment by brine** [comment]
I think we should keep deck sharing as a sub feature though

**Comment by brine** [comment]
nvm I cant read

**Comment by brine** [comment]
this can't be merged anymore since the deck editor files were moved to jodsengine

**Pull request closed without merging**
