### PR TITLE
Normalize all the new lines to match .gitattributes

### PR DESCRIPTION
**Pull request by rstarkov**
This change fixes all the files which have one type of line ending specified in .gitattributes, but a different type actually committed.

Git allows .gitattributes to specify newlines that don't actually match what's in the repository. It should really require any changes to .gitattributes to also submit matching newline changes, but unfortunately it doesn't. When the two go out of sync, Git starts seeing non-existent changes everywhere. What's worse, git doesn't know how to revert them, which makes certain operations completely impossible (like a rebase that touches one of the inconsistent files).

An alternative to changing all of these files is to change .gitattributes, but now that the repository has both CRLF and LF committed, it doesn't matter what .gitattributes is set to; some clean up will be required either way.

### CODE REVIEW

**Comment by kellyelton** [comment]
What do you mean by it sees non existent changes. I haven't had that experience.

**Comment by rstarkov** [comment]
Hi Kelly. Try these steps to reproduce the problem:

1. git clone https://github.com/kellyelton/OCTGN.git
2. edit \OCTGN\octgnFX\Octgn\Windows\ErrorWindow.xaml
3. git checkout ErrorWindow.xaml - to reset it
4. git status - still shows ErrorWindow.xaml as modified.

This is a problem because I can't revert the file no matter what I do. The contents are reset, but git still considers the file modified. This messes up basic merging, because git refuses to proceed, telling me to commit my changes before I merge.

**Comment by kellyelton** [comment]
Oh right yeah, I've encountered that one. I'd fix that by doing

    git rm --cached -r .
    git reset --hard

I'll have to review the files you did change though, as I think some files can't be changed

**Comment by rstarkov** [comment]
Yes, unfortunately that fix doesn't work when I'm trying to merge things.

I realise this is a large change and it may be difficult to change some files, so feel free to reject this pull request and fix only a subset of the files. This is a real problem though, because a mismatch between the files and the .gitattributes declaration is handled by git very, very badly.

So hopefully you'll be able to commit fixed line endings at least for some of the files, and for those you can't, maybe exceptions can be added to .gitattributes, which would also fix the problem.

**Comment by kellyelton** [comment]
Yeah I'm reviewing it now and will post back.

**Comment by kellyelton** [comment]
Ok the first thing if you would, is can you remove all the changes to the project agsxmpp?

The only reason I have that locally is because I made a few changes to it, but otherwise it isn't our project, and I'd like to have only real changes in its history.

Second change would be to ignore those xml files in the packages folder. Those get created by nuget, doesn't really make sense that we'd be changing them or anything.

Other than that it looks fine.

**Comment by kellyelton** [comment]
Also if you could sign this https://www.clahub.com/agreements/kellyelton/OCTGN before I pull.

**Comment by kellyelton** [comment]
Actually before you sign, we have to make a few modifications

**Comment by kellyelton** [comment]
Ok you can sign now.

**Comment by kellyelton** [comment]
[rebuild]

**Comment by kellyelton** [comment]
[Automated Message] You can download the installer for this build here http://www.octgn.net/downloads/releases/pr/OCTGN-Test-Setup-1385.exe

**Comment by rstarkov** [comment]
Updated as requested. Happy to make any further changes if necessary.

**Comment by kellyelton** [comment]
Thanks I'll look at it soon here. You'll notice I've already removed that
agsxmpp lib from the test branch.

**Comment by kellyelton** [comment]
Hey hate to bug you again about this, but we moved the repo to octgn/OCTGN instead of kellyelton/OCTGN, which requires you to sign that document one more time.

https://www.clahub.com/agreements/octgn/OCTGN

Sorry about that. I'll also take a look at your PR and update you.

**Comment by kellyelton** [comment]
Yeah once you sign again it'll be good.

**Comment by kellyelton** [comment]
Thanks again

**Pull request merged**
